import Link from 'next/link'
import ModuleInteraction from './ModuleInteraction.client'
import Localized from '@/components/language/Localized'

type Node = { id: string; title: string; code: string; x: number; y: number; future?: boolean; items: { label: string; href: string; tag?: string }[] }

const nodes: Node[] = [
  { id: 'research', title: 'Research', code: 'MOD-01', x: 50, y: 11, items: [{ label: 'SPMamba — 3-source speech separation', href: '/projects/spmamba-3-source' }, { label: 'MossFormer 2 — three-source separation', href: '/projects/mossformer-2' }] },
  { id: 'systems', title: 'Systems', code: 'MOD-02', x: 14, y: 36, items: [{ label: 'Cisco Networking', href: '/projects/cisco-networking-projects' }] },
  { id: 'edge-ai', title: 'Edge AI', code: 'MOD-03', x: 86, y: 36, items: [{ label: 'Edge AI Stethoscope', href: '/projects/edge-ai-stethoscope', tag: 'Research prototype' }, { label: 'Face Recognition', href: '/projects/face-recognition' }] },
  { id: 'electronics', title: 'Electronics', code: 'MOD-04', x: 14, y: 78, items: [{ label: 'Signal Processing', href: '/about#exploring' }, { label: 'Embedded Systems', href: '/about#exploring' }] },
  { id: 'uav-nav', title: 'UAV Navigation', code: 'DIR-01', future: true, x: 50, y: 82, items: [{ label: 'GPS / GNSS positioning', href: '/about#uav-navigation' }, { label: 'IMU + barometer + compass', href: '/about#uav-navigation' }, { label: 'Sensor fusion / EKF', href: '/about#uav-navigation' }, { label: 'Waypoint + Return-to-Home', href: '/about#uav-navigation' }, { label: 'RTK / precision GNSS', href: '/about#uav-navigation' }] },
  { id: 'ic-design', title: 'IC Design', code: 'MOD-05', future: true, x: 86, y: 78, items: [{ label: 'FPGA', href: '/about#future-directions' }, { label: 'PCB', href: '/about#future-directions' }, { label: 'RF / Antenna', href: '/about#future-directions' }, { label: 'IC Design', href: '/about#future-directions' }] },
]

const moduleHref: Record<string, string> = { research: '/research', systems: '/projects?domain=systems', 'edge-ai': '/projects?domain=edge-ai', electronics: '/projects?domain=electronics', 'uav-nav': '/about#uav-navigation', 'ic-design': '/about#future-directions' }

function Identity() { return <svg viewBox="0 0 320 230" className="h-auto w-[250px] lg:w-[320px]" aria-hidden="true"><ellipse cx="160" cy="182" rx="120" ry="22" fill="var(--iso-shadow)"/><polygon points={oct(108,34)} fill="var(--iso-right)" stroke="var(--iso-edge)" strokeWidth="0.9"/>{Array.from({length:8},(_,i)=>{const a=Math.PI/4*i+Math.PI/8,x=160+Math.cos(a)*108,y=96+Math.sin(a)*108*.5;return <line key={i} x1={x} y1={y} x2={x} y2={y+34} stroke="var(--iso-edge)" strokeWidth="0.8"/>})}<polygon points={oct(108,0)} fill="var(--iso-top)" stroke="var(--iso-edge)" strokeWidth="1"/><polygon points={oct(96,0)} fill="none" stroke="var(--iso-edge)" strokeWidth="0.5" opacity="0.6"/><polygon points={oct(62,0)} fill="var(--iso-dark)"/><polygon points={oct(52,-8)} fill="var(--iso-dark-2)"/>{Array.from({length:8},(_,i)=>{const a=Math.PI/4*i+Math.PI/8;return <circle key={i} cx={160+Math.cos(a)*100} cy={96+Math.sin(a)*100*.5} r="2.4" fill="none" stroke="var(--iso-edge)" strokeWidth="0.9"/>})}{[-1,0,1].map((i,index)=><circle key={i} className="map-led" data-map-led="identity" style={{'--map-led-index':index} as React.CSSProperties} cx={160+i*12} cy="132" r="2.2" fill="var(--iso-led)"/>)}<text x="160" y="96" textAnchor="middle" fontFamily="var(--font-sans)" fontSize="30" fontWeight="600" letterSpacing="4" fill="var(--iso-top)">HN</text></svg> }
function oct(r: number, t: number) { return Array.from({length:8},(_,i)=>{const a=Math.PI/4*i+Math.PI/8;return `${(160+Math.cos(a)*r).toFixed(1)},${(96+Math.sin(a)*r*.5+t).toFixed(1)}`}).join(' ') }
function ModuleIcon({ dashed }: { dashed?: boolean }) { const edge='var(--iso-edge)'; return <svg viewBox="0 0 190 156" className="h-auto w-[150px] lg:w-[184px]" aria-hidden="true"><ellipse cx="95" cy="140" rx="78" ry="15" fill="var(--iso-shadow)"/><polygon points="8,56 95,104 95,136 8,88" fill="var(--iso-left)" stroke={edge} strokeWidth="0.8"/><polygon points="182,56 95,104 95,136 182,88" fill="var(--iso-right)" stroke={edge} strokeWidth="0.8"/>{[0,1,2,3].map(i=><line key={i} x1={150-i*13} y1={73+i*7} x2={150-i*13} y2={97+i*7} stroke={edge} strokeWidth="1.4" opacity="0.55"/>)}<polygon points="95,8 182,56 95,104 8,56" fill="var(--iso-top)" stroke={edge} strokeWidth="0.9" strokeDasharray={dashed?'5 4':undefined}/><polygon points="95,17 172,56 95,95 18,56" fill="none" stroke={edge} strokeWidth="0.5" opacity="0.6"/><polyline points="40,56 60,45 78,55 96,45" fill="none" stroke={edge} strokeWidth="0.8" opacity="0.7"/><polyline points="104,74 120,65 138,74" fill="none" stroke={edge} strokeWidth="0.8" opacity="0.7"/>{[{cx:95,cy:20},{cx:24,cy:56},{cx:166,cy:56},{cx:95,cy:92}].map(p=><g key={`${p.cx}-${p.cy}`}><circle cx={p.cx} cy={p.cy} r="2.6" fill="none" stroke={edge} strokeWidth="0.9"/><line x1={p.cx-1.6} y1={p.cy} x2={p.cx+1.6} y2={p.cy} stroke={edge} strokeWidth="0.8"/></g>)}<polygon points="95,40 133,61 95,82 57,61" fill="var(--iso-dark-2)"/><polygon points="57,61 95,82 95,90 57,69" fill="var(--iso-dark-2)"/><polygon points="133,61 95,82 95,90 133,69" fill="var(--iso-dark)"/><polygon points="95,32 133,53 95,74 57,53" fill="var(--iso-dark)"/><polygon points="95,38 123,53 95,68 67,53" fill="none" stroke="var(--iso-led)" strokeWidth="0.6" opacity="0.5"/>{[0,1,2].map(i=><circle key={i} className="map-led" data-map-led="module" style={{'--map-led-index':i} as React.CSSProperties} cx={105+i*9} cy={78+i*5} r="2" fill="var(--iso-led)"/>)}</svg> }
function List({ node, mobile = false }: { node: Node; mobile?: boolean }) { return <div className={`${mobile ? 'min-w-0 flex-1' : 'mt-2 w-[190px] lg:w-[220px]'} ${!mobile && node.x>60?'text-right':'text-left'}`}><div className="flex items-baseline justify-between gap-2 border-b border-rule pb-1"><h3 className="text-sm font-semibold tracking-tight"><Link className="map-node-title" href={moduleHref[node.id]}>{node.title}</Link></h3><span className="label-mono">{node.future?<Localized en="FUTURE" vi="TIẾP THEO" />:node.code}</span></div><ul className="mt-2 space-y-0.5">{node.items.map(item=><li key={item.label}><Link href={item.href} className="group flex items-baseline gap-2 py-0.5 text-xs leading-snug text-muted-foreground transition-colors hover:text-foreground"><span className="mt-[0.35rem] h-px w-3 shrink-0 bg-rule transition-colors group-hover:bg-accent"/><span className="min-w-0">{item.label}{item.tag&&<span className="label-mono mt-0.5 block">{item.tag}</span>}</span></Link></li>)}</ul>{node.future&&<p className="label-mono mt-2"><Localized en="Next / future directions" vi="Hướng tiếp theo / tương lai" /></p>}</div> }
export default function LovableSystemMap() { return <section aria-label="System map"><div className="map-interactive relative hidden aspect-[16/11] w-full grid-paper md:block"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full pointer-events-none" aria-hidden="true">{nodes.map(n=><line key={n.id} data-map-cable={n.id} x1="50" y1="50" x2={n.x} y2={n.y} stroke="var(--iso-cable)" strokeWidth="1" vectorEffect="non-scaling-stroke" strokeDasharray={n.future?'6 5':undefined} opacity="0.8"/>)}</svg><div data-map-node="identity" className="absolute flex -translate-x-1/2 -translate-y-1/2 flex-col items-center" style={{left:'50%',top:'50%'}}><div className="map-node-motion" style={{'--map-index':0} as React.CSSProperties}><ModuleInteraction nodeId="identity" href="/about" label="About Hoang Anh Nguyen"><Identity/></ModuleInteraction></div><div className="-mt-2 text-center"><h2 className="text-lg font-semibold tracking-tight lg:text-xl"><Link className="map-node-title" href="/about">Hoang Anh Nguyen</Link></h2><p className="mt-1 text-xs text-muted-foreground"><Localized en="Exploring systems, intelligence, and hardware." vi="Khám phá systems, intelligence và hardware." /></p></div></div>{nodes.map((n,i)=><div key={n.id} data-map-node={n.id} className="absolute flex -translate-x-1/2 -translate-y-1/2 flex-col items-center" style={{left:`${n.x}%`,top:`${n.y}%`}}><div className="map-node-motion" style={{'--map-index':i+1} as React.CSSProperties}><ModuleInteraction nodeId={n.id} href={moduleHref[n.id]} label={`Explore ${n.title}`}><ModuleIcon dashed={n.future}/></ModuleInteraction></div><List node={n}/></div>)}</div><ol className="border-t border-rule md:hidden">{nodes.map((n,i)=><li key={n.id} data-map-node={n.id} className="border-b border-rule py-4"><div className="flex items-baseline gap-3"><span className="label-mono w-8 shrink-0">{String(i+1).padStart(2,'0')}</span><List node={n} mobile/></div></li>)}</ol></section> }
